name: Create release

on:
  workflow_dispatch:
    inputs:
      bump-level:
        description: Version level to be bumped
        default: patch
        required: false
        type: choice
        options:
          - patch
          - minor
          - major


jobs:
  create:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Bump version
        run: yarn release --release-as ${{ github.event.inputs.bump-level }}

  publish-npm:
    needs: [set-commit-hash, lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: ottofeller/github-actions/publish-npm@main
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          dry-run: true